### ISSUE TITLE
Which python version does this repo work with?

### ISSUE THREAD

**Issue by vaibhavgeek** [pncnmnp/Bookmark-Manager#11]
Which python version does this repo work with?

**Comment by pncnmnp** [comment]
Hey there, I believe that when I wrote the code about 4-5 years ago, it was intended for Python 3.5. Are you experiencing any issues with dependencies?

If so, could you please share the issue? I can help you out with it.

**Comment by vaibhavgeek** [comment]
We created our own classifier, this repo helped us with the idea of it, so thanks for this :)
