### ISSUE TITLE
Please add a  README

### ISSUE THREAD

**Issue by masukomi** [pncnmnp/Bookmark-Manager#2]
I have no idea what a "NLP based approach to automatically categorize your bookmarks!" looks like (functionally or visually). What bookmarks is it categorizing? Why does this help? Is this something to do with the bookmarks in my browser, or does it have its own store? Etc. etc. etc.

**Comment by pncnmnp** [comment]
Thanks for raising this issue @masukomi

This repository was created to complement a technical paper I was working on. To read more about how the classification works, you can read my paper here: https://pncnmnp.github.io/blogs/bookmark-classification.pdf. 
I have added a README and requirements file. Hope this is helpful!
